# Configuration file for NGINX (Server)

user www-data; #user the worker processes drop to; master stays root to bind port 443
worker_processes auto; #one worker per available CPU core

events { # nginx don't start without events{}
	worker_connections 768; # max simultaneous connections per worker process - Debian default
}

http {
	include /etc/nginx/mime.types; # maps file extensions to Content-Type headers; without it browsers download CSS instead of applying it
	default_type application/octet-stream;

	server {
	listen 443 ssl;
	ssl_protocols TLSv1.2 TLSv1.3;
	ssl_certificate /etc/nginx/ssl/nginxincep.crt;
	ssl_certificate_key /etc/nginx/ssl/nginxincep.key;

	root /var/www/html; # filesystem path nginx prepends to a request URI.
	server_name afontele.42.fr;
	index index.php index.html index.htm; # ilenames tried in order when a URI resolves to a directory

	location / {
		try_files $uri $uri/ =404; #try to find a file, then a dir, then send an 404 error
	}

	location ~ \.php$ { # ~ = case-sensitive regex match. regex locations are evaluated after prefix locations, so this catches .php before location /
		include snippets/fastcgi-php.conf; # Debian snippet: splits PATH_INFO, guards against arbitrary script execution, and sets SCRIPT_FILENAME so php-fpm knows which file to execute
		fastcgi_pass wordpress:9000; # forwards the request over the FastCGI protocol using port 9000
	}}
}
