# Configuration file for NGINX (Server)

user www-data; #user the worker processes drop to; master stays root to bind port 443
worker_processes auto; #one worker per available CPU core

events { # nginx don't start without events{}
	worker_connections 768; # max simultaneous connections per worker process - Debian default (event loop - epoll)
	# how many connections one worker may hold open. With 4 cores: 4 × 768 ≈ 3072 total.
}

http {
	include /etc/nginx/mime.types;
	default_type application/octet-stream;

	server {
	listen 443 ssl;
	ssl_protocols TLSv1.2 TLSv1.3;
	ssl_certificate /etc/nginx/ssl/nginxincep.crt;
	ssl_certificate_key /etc/nginx/ssl/nginxincep.key;

	root /var/www/html; # Debian's conventional web root
	server_name afontele.42.fr;
	index index.php index.html index.htm;

	location / {
		try_files $uri $uri/ =404; # try_files $uri $uri/ /index.php?$args;
	}

	location ~ \.php$ {
		include snippets/fastcgi-php.conf;
		fastcgi_pass wordpress:9000;
	}}
}
