# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Dockerfile                                         :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: afontele <afontele@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2026/07/10 16:28:32 by afontele          #+#    #+#              #
#    Updated: 2026/07/10 18:40:50 by afontele         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

FROM debian:trixie

COPY srcs/requirements/nginx/nginx.conf

EXPOSE 433